vault_path: "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/reactivist's vault/engineering_brain_fork/Engineering Notes"

# GitHub configuration
github:
  username: "sounak07"
  repo: "backend-engineering"
  branch: "main"

attachments_folder: "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/reactivist's vault/engineering_brain_fork/assets"

output_path: "~/Documents/Projects/backend-engineering"
output_path_resources: "assets"


# Files to include (glob patterns)
include:
  - "**/*.md"

# Files to exclude (glob patterns)
exclude:
  - "**/Templates/**"
  - "**/Daily/**"
  - "**/.obsidian/**"
  - "**/Excalidraw/**"
